---
version: "3"

silent: true

includes:
  c: https://raw.githubusercontent.com/standardloop/taskfiles/refs/heads/main/c.yml #../taskfiles/c.yml

vars:
  SOURCE_FILES:
    - logger.c
  TEST_SOURCE_FILES:
    - logger.test.c
  DYLIB_NAME: libstandardloop-logger.dylib
  DYLIB_HEADER: logger.h

tasks:
  default:
    silent: true
    desc: "Show all avaiable tasks."
    cmds:
      - task --list-all

  # GH_RELEASE_VERSION is set by CI
  release:
    deps:
      - c:release

  test:
    deps:
      - test:run

  test:build:
    cmds:
      - task: c:test:build

  test:run:
    deps:
      - test:build
    cmds:
      - ./{{.TEST_EXECUTABLE_NAME}}

  clean:
    deps:
      - c:test:clean

  fmt:
    deps:
      - c:fmt

  docs:
    deps:
      - c:docs
